### ISSUE TITLE
QUES: Saving Documents

### ISSUE THREAD

**Issue by hansaliyad1** [PDFTron/salesforce-webviewer-attachments#5]
Hello

I am implementing PDFtron in my Salesforce org. I have a form which user fills up and PDFtron webviewer next to it. The form has a submit button which saves the form. I am trying to figure out a way where when a form is submitted, it also saves the document and its annotations. I did find the `saveDocument` and `handleReceiveMessage` functions, but I am not sure how they work. `saveDocument` function is in config_apex.js file and somehow `handleReceiveMessage` function uses `saveDocument` function to get base64 string which is passed Apex class which uses base64 string to save the file and annotations. But, how `handleReceiveMessage` gets triggered? Does this configuration somehow enables a button on webviewer, so the user can click on Save button to save the document? In my case, I have a form submit button which triggers the function that grabs form data and sends it to Apex, but I am not sure how to get the document and its annotations. 

I will really appreciate if you can guide me here.

Thank you!

**Comment by tommywintersr** [comment]
Hello,

Thanks for your message.

You can use your form submit event handler to trigger the save action like so: 

- Notify your `pdftronWvInstance` via [pubsub](https://github.com/PDFTron/salesforce-webviewer-attachments/blob/main/force-app/main/default/lwc/pdftronAttachmentPickerCombobox/pdftronAttachmentPickerCombobox.js#L52)/[LMS](https://developer.salesforce.com/docs/component-library/bundle/lightning-message-service/documentation) or other communication channel. 
- In your pdftronWvInstance make a call to `this.iframeWindow.postMessage` and include a type, for example `({ type: 'FORM_POSTED' }, formData)` - `formData` could be any data you want to optionally pass
- In your `config_apex.js` -> [`receiveMessage`](https://github.com/PDFTron/salesforce-webviewer-attachments/blob/main/force-app/main/default/staticresources/myfiles/config_apex.js#L97) create a new switch case called `FORM_POSTED` where you can call your [`saveDocument()`](https://github.com/PDFTron/salesforce-webviewer-attachments/blob/main/force-app/main/default/staticresources/myfiles/config_apex.js#L32) function.

Some context:
Since WebViewer is hosted in an iframe, we need to use [`postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) function to post data from and to it. Posting messages to it is handled by `receiveMessage` in your `config_apex.js`

Hope that helps!
Thomas

**Comment by hansaliyad1** [comment]
@tommywintersr As always, thank you so much for your message and assistance. Just posting my code here to make sure I understand correctly what you mentioned above.

In my LWC JS file, I have the below Form Submit button handler. This handler checks for errors and if everything looks good then calls `postMessage` function.

```
handleSubmit() {
        this.checkForErrors();
        this.checkForDocument();
        if (this.errors.length === 0 && this.errorsContact.length === 0) {
            this.iframeWindow.postMessage({type: 'FORM_POSTED', formData: ''}, '*')
            //this.notifyUser('Success', 'The form was submitted.', 'success');
        }
    }
```

The call made by the above function is received by `receiveMessage` function in `config.js` file, which then calls `saveDocument()` function which is in `config.js` file as well.

```
function receiveMessage(event) {
  if (event.isTrusted && typeof event.data === 'object') {
    switch (event.data.type) {
      case 'OPEN_DOCUMENT':
        event.target.instance.loadDocument(event.data.file, {
          officeOptions: {
            disableBrowserFontSubstitution: true,
          }
        })
        break;
      case 'OPEN_DOCUMENT_BLOB':
        const { blob, extension, filename, documentId } = event.data.payload;
        event.target.instance.loadDocument(blob, { extension, filename, documentId,
          officeOptions: {
            disableBrowserFontSubstitution: true,
          }
        })
        break;
      case 'FORM_POSTED':
        saveDocument();
        break;
      case 'CLOSE_DOCUMENT':
        event.target.instance.closeDocument()
        break;
      default:
        break;
    }
  }
}
```

Below is `saveDocument()` function. This function generates base64Data and returns the data using `postMessage` function to LWC. The only question I have here is where is docViewer initialized in `const doc = docViewer.getDocument();`. I am asking this because I am getting `Uncaught (in promise) ReferenceError: docViewer is not defined` error in console.

```
async function saveDocument() {
  const doc = docViewer.getDocument();
  if (!doc) {
    return;
  }
  readerControl.openElement('loadingModal');

  const fileType = doc.getType();
  const filename = doc.getFilename();
  const xfdfString = await docViewer.getAnnotationManager().exportAnnotations();
  const data = await doc.getFileData({
    // Saves the document with annotations in it
    xfdfString
  });

  let binary = '';
  const bytes = new Uint8Array(data);
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }

  const base64Data = window.btoa(binary);

  const payload = {
    title: filename.replace(/\.[^/.]+$/, ""),
    filename,
    base64Data,
    contentDocumentId: doc.__contentDocumentId
  }
  // Post message to LWC
  parent.postMessage({ type: 'SAVE_DOCUMENT', payload }, '*');
}
```

In LWC, the returned message from `config.js` `saveDocument()` function is handled by `handleReceiveMessage()` function. This function then calls Apex function in backend.

```
handleReceiveMessage(event) {
        const me = this;
        if (event.isTrusted && typeof event.data === 'object') {
          switch (event.data.type) {
            case 'SAVE_DOCUMENT':
                console.log({ json: JSON.stringify(event.data.payload), recordId: this.recordId })
              //saveDocument({ json: JSON.stringify(event.data.payload), recordId: this.recordId }).then((response) => {
              //  me.iframeWindow.postMessage({ type: 'DOCUMENT_SAVED', response }, '*')
              //}).catch(error => {
              //  console.error(JSON.stringify(error));
              //});
              break;
            default:
              break;
          }
        }
    }
```

Did I understand this correct? Thank you again!!

**Comment by tommywintersr** [comment]
Yes, you got the flow correct. 

One thing you should be aware of is:
`In my LWC JS file, I have the below Form Submit button handler. This handler checks for errors and if everything looks good then calls postMessage function.`

--> You can only call the `postMessage()` function from `pdftronWvInstance` / the LWC that hosts the `iframe`.
ie. if your form lives in a different LWC, you need to send it from your formLWC component to pdftronWvInstance component first, then call `postMessage()` in the iframe LWC.


- [Here](https://github.com/PDFTron/salesforce-webviewer-attachments/blob/main/force-app/main/default/lwc/pdftronAttachmentPickerCombobox/pdftronAttachmentPickerCombobox.js#L52) is a LWC sending data to pdftronWvInstance
- [Here](https://github.com/PDFTron/salesforce-webviewer-attachments/blob/main/force-app/main/default/lwc/pdftronWvInstance/pdftronWvInstance.js#L37) is the handler in your `pdftronWvInstance` file that relays the data to your iframe/config_apex.js file

TW

**Comment by hansaliyad1** [comment]
@tommywintersr Thanks again! I understand what you're saying. In my `handleSubmit` function, I call `fireEvent` function, which fires the event called `formPosted`. I registered the `formPosted` event in `connectedCallback` function. It does call my `saveDocument` function in `config.js` file, but it errors out with message `Uncaught (in promise) ReferenceError: docViewer is not defined` on form submit. Where should initialize `docViewer`?

Thanks again!

**Comment by hansaliyad1** [comment]
> @tommywintersr Thanks again! I understand what you're saying. In my `handleSubmit` function, I call `fireEvent` function, which fires the event called `formPosted`. I registered the `formPosted` event in `connectedCallback` function. It does call my `saveDocument` function in `config.js` file, but it errors out with message `Uncaught (in promise) ReferenceError: docViewer is not defined` on form submit. Where should initialize `docViewer`?
> 
> Thanks again!

@tommywintersr Thanks again for all your time. I was able to solve this error. I used `event.target.instance.docViewer.getDocument();` instead of `docViewer.getDocument();`. That solved the problem I had.

**Comment by hansaliyad1** [comment]
@tommywintersr I am stuck again at `saveDocument` function in `config.js`. I will really appreciate if you can provide me your inputs. After `saveDocument` is executed, it is not able to return the `payload` back to the LWC. I am not seeing any error and I also console.log the payload in `saveDocument` and I can confirm it is getting generated. I believe `parent.postMessage({ type: 'SAVE_DOCUMENT', payload }, '*');` is not able to return event to `handleReceiveMessage` function in LWC. Furthermore, I am not sure where `handleReceiveMessage` function should be created, LWC or WebViewer, but I have `handleReceiveMessage` function at both places and none of them is getting invoked. Am I missing something? Thanks!

**Comment by tommywintersr** [comment]
@hansaliyad1 Good to hear you are progressing. After your `parent.postMessage()` call, make sure your LWC parent component that hosts the WebViewer iframe has a message handler ie `window.addEventListener('message', this.handleReceiveMessage.bind(this), false);` in the `connectedCallback()` to handle your message.

**Comment by hansaliyad1** [comment]
@tommywintersr Thank you so much for your input! That helped! I really appreciate for your time!
